package org.example.springproject.util;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Component
public class JDBCUtils {

    public <T> List<T> executeQuery(Connection conn, String sql, RowMapper<T> rowMapper, Object... params) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            setParameters(ps, params);
            try (ResultSet rs = ps.executeQuery()) {
                List<T> results = new ArrayList<>();
                int rowNum = 0;
                while (rs.next()) {
                    results.add(rowMapper.mapRow(rs, rowNum++));
                }
                return results;
            }
        }
    }

    public int executeUpdate(Connection conn, String sql, Object... params) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            setParameters(ps, params);
            return ps.executeUpdate();
        }
    }

    /**
     * FIX: Use standard JDBC getGeneratedKeys() instead of Spring KeyHolder
     */
    public Integer executeInsertWithAutoGeneratedKey(Connection conn, String sql, Object... params) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            setParameters(ps, params);
            int rows = ps.executeUpdate();

            if (rows > 0) {
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    if (rs.next()) {
                        // Retrieve the first column generated (the ID)
                        // getInt(1) gets the value of the first column in the result set
                        return rs.getInt(1);
                    }
                }
            }
        }
        return null;
    }

    public RowMapper<Map<String, Object>> getGenericRowMapper() {
        return (rs, rowNum) -> {
            Map<String, Object> row = new java.util.HashMap<>();
            int columnCount = rs.getMetaData().getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                String col = rs.getMetaData().getColumnName(i);
                row.put(col, rs.getObject(i));
            }
            return row;
        };
    }

    private void setParameters(PreparedStatement ps, Object... params) throws SQLException {
        if (params != null) {
            for (int i = 0; i < params.length; i++) {
                ps.setObject(i + 1, params[i]);
            }
        }
    }
}